examples/sile-and-markdown.md, inputters/markdown.lua, packages/markdown/init.lua
=> Ability to enable/disable Markdown extensions

examples/sile-and-markdown.md, inputters/markdown.lua, packages/markdown/commands.lua
=> feat: Support implicit figures a.k.a. captioned images

README.md, examples/sile-and-markdown.md, inputters/markdown.lua, packages/markdown/commands.lua
=> Support raw inline HTML br and wbr elements

README.md, examples/sile-and-markdown.md, inputters/markdown.lua, packages/markdown/commands.lua
=> Horizontal dividers

lua-libraries/lunamark/reader/markdown.lua
Closes #11
As we currently still use a "vendored" copy of lunamark here, this is a raw backport to our local vendored copy of the fixes recently applied to the reader (parsing) module.
Notably, it includes (as an all-in-one commit) the following merged PRs:
52 (nested fenced divs)
55 (corner cases for fenced code attributes )
57 (tildes and backticks in infostrings of tilde code blocks) 59 (fenced divs with implicit class names and trailing columns)
And my own initial PR for:
61 (blockquote in fenced div edge case)
(Whether correct or not at this moment, with all of the above this is still largely better than the old code we still had.)
I obviously did not author (all of) these changes, so credit is due (Co-Authored-By tag in the commit)
=> upgrade lunamark reader for fenced divs and code blocks fixed issues

README.md, examples/sile-and-markdown.md, inputters/markdown.lua, inputters/pandocast.lua, lua-libraries/lunamark/reader/markdown.lua, lua-libraries/lunamark/writer/generic.lua, markdown.sile-dev-1.rockspec, packages/markdown/commands.lua
=> Cross references support

README.md, examples/markdown-sile-schema.dot, examples/sile-and-djot.dj, examples/sile-and-markdown-manual.sil, examples/sile-and-markdown.md, inputters/djot.lua, inputters/pandocast.lua, lua-libraries/djot.lua, lua-libraries/djot/ast.lua, lua-libraries/djot/attributes.lua, lua-libraries/djot/block.lua, lua-libraries/djot/filter.lua, lua-libraries/djot/html.lua, lua-libraries/djot/inline.lua, lua-libraries/djot/json.lua, markdown.sile-dev-1.rockspec, packages/djot/init.lua, packages/markdown/commands.lua, packages/markdown/init.lua
=> feat: add Djot support (WIP from quick experimentation)

inputters/djot.lua, inputters/markdown.lua, inputters/pandocast.lua, packages/markdown/commands.lua, packages/markdown/utils.lua, packages/pandocast/init.lua
=> fix: non-breakable space shall have variable width for justification

README.md
=> Correct some typos in README

inputters/djot.lua
=> fix: Incorrect header identifier in nested blocks in Djot

examples/sile-and-djot.dj, examples/sile-and-markdown-manual.sil, inputters/djot.lua
=> feat: Add predefined symbols and external metadata passing in Djot

examples/sile-and-djot.dj, inputters/djot.lua, packages/markdown/commands.lua
=> fix: Handle attributes on note references in Djot

markdown.sile-dev-1.rockspec, packages/markdown/commands.lua, packages/markdown/utils.lua
=> fix: Honor qualified BCP47 language to get correct smart quotes

examples/sile-and-djot.dj, examples/sile-and-markdown-backcover.dj, examples/sile-and-markdown-manual-styles.yml, examples/sile-and-markdown.md, inputters/djot.lua, inputters/markdown.lua, inputters/pandocast.lua, packages/markdown/commands.lua
=> feat: Support class or package provided definition environment

.github/workflows/luacheck.yml, .luacheckrc, inputters/markdown.lua, inputters/pandocast.lua, lua-libraries/djot/json.lua, lua-libraries/lunamark/reader/markdown.lua, markdown.sile-1.5.1-1.rockspec
See https://github.com/Omikhleia/resilient.sile/pull/70
=> Lua 5.1 minimum compatibility

examples/final-notes.dj, examples/sile-and-djot.dj, examples/sile-and-markdown-manual.silm, examples/sile-and-markdown.md, packages/djot/init.lua, packages/markdown/cmbase.lua, packages/markdown/init.lua
=> feat: Support bare percentage in width and height options

lua-libraries/lunamark/util.lua, packages/markdown/commands.lua, rockspecs/markdown.sile-2.1.0-1.rockspec
See https://github.com/Omikhleia/silex.sile/issues/11
Closes #117
=> refactor: Compatibility upgrade with SILE 0.15

inputters/pandocast.lua
=> feat(pandocast): Support Pandoc 3.1+ implicit figures

packages/markdown/utils.lua
=> fix: Broken embedders detection for rendered code blocks

lua-libraries/djot/ast.lua, lua-libraries/djot/attributes.lua, packages/markdown/commands.lua
See https://github.com/jgm/djot/discussions/277#discussioncomment-14213563 for the whole picture.
=> feat: Support a Djot extension for marking indexed terms

examples/sile-and-djot.dj, examples/sile-and-markdown.md
=> docs: Support markup for indexed terms
