Omikhleia/markdown.sile

- README.md
- examples/sile-and-markdown-manual.sil
- examples/sile-and-markdown.md
- inputters/markdown.lua
- lua-libraries/lunamark/reader/markdown.lua
- packages/markdown/init.lua
Native markdown support for:
- Standard hard line breaks (two trailing spaces at end of line)
- Pandoc-like escaped line breaks (a blackslash at end of line).
This PR also includes
- Raw (inline) Markdown support in SILE documents
- Better docs.
> Hard line breaks

- packages/markdown/commands.lua
Closes #39
Whether that change in processString("rawtext", "sil") in SILE v0.14.6 was expected or not, it broke our way of handling raw Markdown blocks so we need a hotfix/workaround.
> fix: compatibility fix with SILE 0.14.6 breaking raw blocks

- README.md
- examples/sile-and-markdown.md
- inputters/markdown.lua
- packages/markdown/commands.lua
Adds:
- `smart_primes` custom extension, which leverages `smarts` with support for prime marks (e.g. `45' 7"` --> 45′ 7″)
- `.decimal` pseudo-class attribute on span elements, for numbers in the content to be formatted accordingly with (current) language-specific rules (e.g. `[1234567.8]{.decimal}` --> 1,234,567.8 in English, 1 234 567,8 in French)
> Smarter typography (smart prime marks, decimal numbers)

- README.md
- examples/sile-and-markdown.md
- inputters/markdown.lua
- inputters/pandocast.lua
- lua-libraries/lunamark/reader/markdown.lua
- packages/markdown/commands.lua
> feat: Math support

- examples/sile-and-markdown.md
- markdown.sile-dev-1.rockspec
- packages/markdown/commands.lua
Closes #9 
N.B. I didn't implement LilyPond support (so provided by the embedders module), because 
- its quite marginal (not supported in many markdown renderer)
- there are security concerns, as mentioned in the embedders module documentation
- my embedder is still a bit experimental
DOT is cool enough.
> feat: Support Graphviz DOT in images and fenced code blocks

- examples/sile-and-djot.dj
- examples/sile-and-markdown.md
- lua-libraries/lunamark/reader/markdown.lua
E.g. it was not allowing characters found in usual SILE dimensions, such as "50%lw" or "3.5cm".
Closes #49 
This is kind of workaround here on our vendored lunamark copy - the issue is reported upstream to it, but I am not sure I read the Pandoc haskell code well enough for a proper (= complete and safe) resolution.
> fix: too restrictive native Markdown attribute parsing

- examples/sile-and-djot.dj
- examples/sile-and-markdown-manual.sil
- examples/sile-and-markdown.md
- inputters/djot.lua
- packages/markdown/commands.lua
Closes #51 
Disabling element numbering and/or addition to the ToC (for lists of figures or tables) when `.unnumbered` and resp. `.notoc` pseudo-classes are used.
For captioned figures, it works with Markdown, Randoc AST and Djot.
For captioned tables, it works with Djot only, as the latter allows attributes on any element (here the table), but regular Markdown does not have that capability.
> feat: propogate .unnumbered and .notoc on captioned elements

- inputters/djot.lua
- inputters/markdown.lua
- inputters/pandocast.lua
Closes #53 
Rounding table width at 99.9% rather than 100%
This is an acceptable workaround:
- Hardly visible
- There's already some rounding in effect (due to the float precision .5f on each column)
- The table/cell borders are anyway a bit off (see ptable, the bottom and right borders are drawn "outside" the box to ensure proper overlapping)
> Centered envs introduce vertical spaces in tables (workaround)

- packages/markdown/commands.lua
Instead of using the default **lists** package from SILE, so that to benefit from advanced features and styling in that context.
Also, this avoids loading the **lists** package when the (command-wise compatible) **resilient.lists** package is available/loaded, so the commands won't get overridden.
(It won't fully avoid users to explicitly load **lists** and cause potential discrepancies or not meeting expectations afterwards, but that's a different topic.)
Closes #58
> fix: load resilient.lists when used in resilient classes

- examples/sile-and-markdown-manual-styles.yml
- examples/sile-and-markdown-manual.sil
- examples/sile-and-markdown.md
- packages/markdown/commands.lua
Closes #59
Some separation of concerns question here: whether markdown.sile should (as it does here and in previous commits) check for resilient support, or whether resilient.sile should be responsible for overriding some behavior at appropriate hooks...
Since we already started having some feature-detection based logic, I went for the first case, which is the most straightforward. Future will tell....
I tend to think that playing fair with other (non-resilient compatible) classes was good decision initially: people install SILE, install markdown.sile and it just works out-of-the-box, even with the limited standard book class from SILE.
Yet, it's harder and harder to propose good and interesting concepts if we stick to the latter only here. The resilient implementations are already …
> Custom styles in resilient context

- inputters/djot.lua
That is: `strong`, `emph`, `double_quoted` and `single_quoted`.
Marked as a bug: we produced a warning here, but it clearly doesn't meet the expectations.
So now these are supported, for instance, instead of producing a warning:
```
*strong*{.underline} or _emphasis_{.smallcaps}
"text"{lang=fr} or 'text'{lang=fr}
```
There's a small catch maybe:
- For strong and emphasis, the attributes are applied around the content, before applying the font change (so that font-related attributes are evaluated in the expected context, e.g. underlining or striking out may use font properties)
- For quotes, the attributes are applied around the quoted content, i.e. after applying the quotes (so that language change as show here produces the right quotation marks in the target language).
> fix: support Djot attributes on more inline elements

- examples/sile-and-djot.dj
- packages/markdown/commands.lua
for consistency with our native Markdown approach, and because we want the default behavior to be typographically sound, we even stated it!
So we introduce `.fullrule` for users who really want it, but they now have to make it explicit, and we remove our `.rule` since it becomes the default.
Nice 20% rule:
```
---
```
Ugly full rule:
```
{.fullrule}
---
```
Not considered a breaking change as the default wasn't very consistent with what we did in Markdown. And I don't care, full rules are ugly lol.
> fix: change default to the 20% rule for thematic break in Djot

- examples/sile-and-djot.dj
- examples/sile-and-markdown.md
- packages/markdown/commands.lua
Because most of the time it's quite bad to have a line-break hyphenation in the middle of a proper name... and it might be more acceptable to have a poorly justified line (e.g. stretched, with proper emergency stretch settings) than to allow the hyphenation there...
> feat: add .nobreak pseudo-class on span/inline elements

- examples/sile-and-markdown.md
- packages/markdown/commands.lua
- packages/markdown/utils.lua
We only processed the id and the src, but other attributes are interesting to propagate as in a span (styles, etc.)
Closes #67
> fix: honor more attributes on direct links

- examples/sile-and-djot.dj
- examples/sile-and-markdown.md
- packages/markdown/commands.lua
Or "how can I get nice poetry in my book typeset in Djot while the latter has no line blocks yet"
> feat: render fenced code blocks marked as markdown or djot

- examples/sile-and-djot.dj
- inputters/djot.lua
Kind of a "hack" from the idea sketched at https://github.com/jgm/djot/issues/35#issuecomment-1534724327 using pseudo-footnotes and symbols for content substitution.
Call that tweaking a language! Whatever can happen will happen ;-) :rofl: :rofl: 
Quick test document
```
[^:author:]: Herbert _"Froggie"_ Pumpernickel{.smallcaps}
[^:abstract:]: This is my abstract.
It spans on several{.underline} paragraphs.
Which is _cool_.
Take a deep breath of O~2~ and smile.
[^:lorem:]: `\use[module=packages.lorem]\lorem[words=10]`{=sile}
{custom-style=center}
:::
A really cool article
:author:
:::
> :abstract:
This is :author: speaking: ":lorem:."
```
Rendered:
> feat: Use Djot symbol and pseudo-footnotes for variable substitution

- examples/sile-and-markdown.md
- inputters/djot.lua
- inputters/markdown.lua
- lua-libraries/lunamark/reader/markdown.lua
- packages/markdown/commands.lua
- Added `==mark==` support to the native Markdown (vendored lunamark + markdown package)
- Refactor slightly the native djot package to use common logic
- Nothing done for the pandocast package, but if I correctly read the incoming change, Pandoc expands it as a Span so we get it for free.
> Support highlighting (==mark==) in Markdown

- lua-libraries/lunamark/reader/markdown.lua
Introduced in 0139e114b9cbc6df017e2a64a9487d43a57d76f4 = that small dot was overlooked
> fix: lunamark regression on smart ellipses since math support was introduced

- lua-libraries/lunamark/reader/markdown.lua
Backported from my own PR to lunamark: https://github.com/jgm/lunamark/pull/68
> fix: lunamark Pandoc-like attributes are too restrictive

- examples/sile-and-djot.dj
- examples/sile-and-markdown-manual-styles.yml
- inputters/djot.lua
- lua-libraries/djot/ast.lua
- packages/markdown/commands.lua
Exprimental attributed quotes or epigraphs:
Extending the Djot reader to process a caption on a blockquote:
```
> Some quote...
> Lorem ipsum...
^ Quote source as a caption
```
See discussion https://github.com/jgm/djot/issues/28#issuecomment-1535554065 for the possibility of generalizing captions...
Only applied to blockquotes only in this PR, as I need a "quick" solution for epigraphs -- there would be other ways to do it eventually, so let's aim at something simple to start with.
> Djot epigraph extension feature

- packages/markdown/commands.lua
Kind of an edge case, but this may happen more easily when using resilient and its style paradigm: Span expansion (in a possible cascade of styling) used the (equivalent of the) `SILE.call("...", ..., function() ... end)` programming paradigm.
This does cause an issue actually when some low-level commands there involve input filters or anything working directly on the text element in an AST content (text casing, sub/superscript faking, etc.)
Easy way to cause the issue:
```
This is [super ==script==]{ custom-style=textsuperscript }
```
If using such function calls, this either fails with an error (because textsuperscript assumes an AST content, not a function) or doesn't do the expected things anyway.
On the other hand, it does work if we use the `SILE.call("...", ..., { ... })` …
> Command cascades should build an AST instead of functions

- classes/markdown.lua
- examples/introduction.md
- examples/sile-and-djot.dj
- examples/sile-and-markdown-manual.sil
- examples/sile-and-markdown.md
- examples/sile-and-pandoc.dj
- inputters/djot.lua
- inputters/markdown.lua
- inputters/pandocast.lua
- packages/markdown/commands.lua
Inputter option `shift_headings`:
> Header shifting option for Markdown, Djot, Pandoc AST

- examples/sile-and-markdown-manual.sil
- inputters/djot.lua
- lua-libraries/djot/block.lua
- lua-libraries/lunamark/reader/markdown.lua
- packages/markdown/commands.lua
- Closes #82 (backport)
- Closes #85 (backport)
- Update PDF metadata in the manual
- (Djot) Cancel SILE's ToC header for feature parity whether using SILE's core ToC and resilient's ToC packages
> Minor tweaks and backported fixes

- examples/sile-and-djot.dj
- examples/sile-and-markdown-manual-styles.yml
- examples/sile-and-markdown.md
- inputters/djot.lua
- lua-libraries/djot/attributes.lua
- lua-libraries/djot/block.lua
Initially an experimental proposal.
Refer to https://github.com/jgm/djot/issues/238
Moving forward:
Needing some minimal templating strategy for resilient.sile v2.2 "bookmatter" feature, and this is sound enough to start with.
> feat: Djot extension for symbol-based conditionals

- examples/sile-and-djot.dj
- packages/markdown/commands.lua
Doing this in Markdown by specializing more "divider sequences" as we already do would have been messy.
No reason not to pass Djot attributes to the underlying package, however!
> Allow all 'couyards' pendants in Djot (passing attributes)

- packages/markdown/commands.lua
I have tested it on the default class and a `classes.test` class defined as follows:
```lua
local book = require("classes.resilient.book")
local class = pl.class(book)
class._name = "test"
function class:_init (options)
book._init(self, options)
self:loadPackage("markdown")
end
return class
```
As an input file, I used this short `hello.md`:
```markdown
Hello, world!
```
When I ran `sile -u inputters.markdown hello.md` and `sile -u inputters.markdown -c classes.test hello.md`, then in the first case I got a non-resilient class warning and in the second case I got none.
> feat: improve resilient class detection

- markdown.sile-1.5.2-1.rockspec
- packages/markdown/commands.lua
It loaded the whole of the extensions provided by silex.sile, which is not what we wanted outside the resilient usage. It behaves badly with silex.sile 0.4 as overrides would now come too late possibly, causing havoc...
A quick workaround for #107 which would deserve a cleaner solution...
> fix: Do not load the resilient base class for feature detection

- .gitignore
- .luacheckrc
- inputters/djot.lua
- inputters/markdown.lua
- inputters/pandocast.lua
- packages/markdown/commands.lua
- packages/markdown/utils.lua
- refactor: AST utilities are in SU.ast in SILE 0.15-develop and silex.ast provides our compatibility layer for these with SILE 0.14.x, so it an obvious change for the future.
- fix: Improve error handling in Djot to report location details
The latter _greatly_ improves debugging... Now we get line and colum, and stack details:
```
! Ignoring unattached attribute near [[…x {.loose}]] at temp/test.dj: in <snippet>:
[[{lang="en-GB"}␤:::␤␤Later on...␤x {.loose}␤␤:toto:␤␤--- "Hello world"[^1]␤␤--- Lorem ipsum dolor con]]
! Symbol 'toto' was not expanded (no corresponding metadata found) at temp/test.dj:7:1: in symbol
! Failure to find footnote '1' at temp/test.dj:9:18: in footnote_reference
error summary:
Processing at: temp/test.dj:9:18: in footnote_reference
```
Or with `-t` (snippet):
``` …
```
> Improve logging and refactor AST utilities

- README.md
- examples/sile-and-pandoc.dj
- inputters/pandocast.lua
- rockspecs/markdown.sile-2.2.0-1.rockspec
Alternative to luajson for JSON parsing.
Closes #104
Closes #21 
The documentation now says what to do for luajson; and lunajson as Lua-only module also works and will be made the default dependency.
> feat(pandocast): Support the lunajson parsing library as alternative

- rockspecs/markdown.sile-2.2.0-1.rockspec
> fix: Correct version of textsubsuper.sile dependency for SILE 0.15

- examples/sile-and-djot.dj
- inputters/djot.lua
- packages/markdown/commands.lua
Obviously needs SILE > 0.15, but it was indeed easy to just pass through the attributes to SILE.
Closes #81 
With some unrelated rewording here and there in the documentation, I'm told I am "too verbose" sometimes. Doh.
> feat(djot): Support attributes for numbered display math equations

- examples/sile-and-djot.dj
- inputters/djot.lua
- packages/markdown/commands.lua
> feat(djot): Support programmatic symbols (extensible via Lua)

- README.md
- examples/extra-styles.dj
- examples/markdown-djot.bib
- examples/sile-and-djot.dj
- examples/sile-and-markdown-manual-styles.yml
- examples/sile-and-markdown.md
- inputters/djot.lua
- inputters/markdown.lua
- inputters/pandocast.lua
- lua-libraries/djot/ast.lua
- lua-libraries/djot/inline.lua
- packages/markdown/commands.lua
- packages/markdown/utils.lua
Closes #10 
We'd need https://github.com/sile-typesetter/sile/issues/2196 to go futher, but this is a good start for basic citations anyway.
- (Djot) Add to the the Djot parser a "naive rule" for `[@ ... ]` (= regular citations, no "in-text" citation, and no "suppress-author"
- (Markdown) Override the Lunamark Citations to use the same logic
- (Pandoc AST) Ignore the parsed citations, and reconstruct a string from the inlines, so that we can support the same logic too.
> feat: Citations basic support

- inputters/djot.lua
- packages/markdown/commands.lua
So the latter might implement a different behavior depending on them. As of now, SILE's default blockquote (from SILE 0.15.0) and resilient's style-aware blockquote don't support options, so this would not do anything yet, but it paves the way for more customization or alternate implementations.
N.B. It's also what we were already doing for the captioned quotes (via the epigraph environment, which does support several options), so it also fixes a small API discrepancy...
_Rationale:_
See discussion https://github.com/Omikhleia/markdown.sile/discussions/138
> fix: Propagate Djot attributes to the blockquote implementation

- packages/markdown/commands.lua
- rockspecs/markdown.sile-2.3.2-1.rockspec
The issue as found via the resilient manual revamping https://github.com/Omikhleia/resilient.sile/pull/122
(whatever unicode symbol is U+xxxx)
```
[^:some-macro:]: ^:U+xxxx:^
This is :some-macro: and again :some-macro:
```
We are modifying by side effect the options, and an error occurs on the second occurrence.
I don't like shallow copying lists for no obvious reasons, but there seems to be other cases that could be affected too, and I lack time for investigating them...
> fix: Djot user-defined pseudo-symbols nesting issue

- README.md
- examples/markdown-sile-overview.dot
- examples/markdown-sile-schema.dot
- examples/sile-and-djot.dj
- examples/sile-and-markdown-manual-styles.yml
- examples/sile-and-markdown.md
- packages/markdown/commands.lua
- rockspecs/markdown.sile-2.4.0-1.rockspec
Closes #4 
Needs: https://github.com/Omikhleia/highlighter.sile/pull/1
> feat: Rely on highligher.sile for syntax highlighting in code blocks

- .gitignore
- README.md
- examples/introduction.dj
- examples/markdown-djot.bib
- examples/sile-and-markdown-manual.silm
- inputters/djot.lua
- inputters/markdown.lua
- inputters/pandocast.lua
- packages/djot/init.lua
- packages/markdown/cmbase.lua
- packages/markdown/commands.lua
- packages/markdown/init.lua
- packages/markdown/utils.lua
- packages/pandocast/init.lua
- rockspecs/markdown.sile-3.0.0-1.rockspec
Stop supporting older SILE 0.14.x and 0.15.y (y <= 12).
Remove dependency on the silex compatibility layer.
Remove some compatibility fallbacks for earlier versions of SILE.
Update in-code documentation to LDoc (rather than the VSCode emma-based stuff).
Closes #148
> refactor!: Remove silex compatibility layer and some SILE shims
